### ISSUE TITLE
Continuous 1.4W power

### ISSUE THREAD

**Issue by selman-nus** [taichunmin/waveshare-epd-demo#1]
Hi Taichunmin,
I am trying to use this board to power up my NFC sensor. I only need the board to continuously transmit 1.4 W power out. It doesn't have to be reading any value from the sensor. 

I checked the built-in "NFC Test Demo" but it is not continuous, it is blinking. And also doesn't seem like high power, not 1.4 W for sure. 

Do you know how to make this board transmit continuous 1.4 W power out?

**Comment by taichunmin** [comment]
Sorry, I don't have this board. The source code fork from waveshare.
https://www.waveshare.net/wiki/ST25R3911B_NFC_Board
